spring.application.name=jac
server.port=8080
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.security=${JAC_LEVEL_LOGIN:DEBUG}

spring.r2dbc.username=${JAC_DATASOURCE_USERNAME}
spring.r2dbc.password=${JAC_DATASOURCE_PASSWORD}
spring.r2dbc.url=${JAC_DATASOURCE_URL}
